# Generated by Django 5.0.3 on 2024-04-03 14:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id_aluno', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=255)),
                ('responsavel', models.CharField(max_length=255)),
                ('idade', models.IntegerField()),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
